version: "2"

services:
  vote:
    #build: ./vote
    image: kamigerami/vote_app
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"

  redis:
    image: redis:alpine
    ports: ["6379"]

  worker:
    #build: ./worker
    image: kamigerami/worker_app

  db:
    image: postgres:9.4

  result:
    #build: ./result
    image: kamigerami/result_app
    command: nodemon --debug server.js
    volumes:
      - ./result:/app
    ports:
      - "5111:80"
      - "5858:5858"
